version: '3.7'

services:
    laboratory:
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        volumes:
            - .:/home/node/app
        container_name: laboratory
        expose:
            - '4000'
        ports:
            - '4000:4000'
        stdin_open: true
        tty: true
        command: sh -c "yarn typeorm migration:run && yarn dev"
        networks:
            laboratory:
                ipv4_address: 192.168.50.5
        depends_on: 
            - database

    database:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - '3306:3306'
        restart: always 
        volumes:
            - 'apidata:/var/lib/mysql'
        container_name: database
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=laboratoryApi
        networks:
            laboratory:
                ipv4_address: 192.168.50.6

networks:
    laboratory:
        ipam:
            config:
                - subnet: 192.168.50.0/24

volumes:
    apidata:
        driver: local